version: "3.3"

services:

    nginx:
        container_name: nginx.diplom
        image: nginx:1.24-alpine
        ports:
            - ${APP_PORT:-8098}:80
        depends_on:
            - php
        volumes:
            - ./docker/conf/vhost.conf:/etc/nginx/conf.d/default.conf:ro
            - ./:/var/www/html:rw,delegated

    php:
        container_name: php.diplom
        build:
            context: .
            dockerfile: docker/Php.Dockerfile
        volumes:
            - ./:/var/www/html:rw,delegated
        depends_on:
            - mysql

    mysql:
        container_name: mysql.diplom
        image: mysql:8.0
        ports:
            - ${DB_DOCKER_PORT:-33061}:3306
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
